-- MySQL Script generated by MySQL Workbench
-- Mon May 15 23:00:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema elma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elma` DEFAULT CHARACTER SET utf8 ;
USE `elma` ;

-- -----------------------------------------------------
-- Table `elma`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`roles` (
  `code` VARCHAR(50) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `employee` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elma`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `address` VARCHAR(250) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `inn` VARCHAR(12) NULL,
  `rs` VARCHAR(20) NULL,
  `bik` VARCHAR(10) NULL,
  `chifNane` VARCHAR(250) NULL,
  `contactName` VARCHAR(250) NULL,
  `contactPhone` VARCHAR(50) NULL,
  `companyEmail` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elma`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`users` (
  `login` VARCHAR(50) NOT NULL,
  `customerId` INT NOT NULL,
  `roleCode` VARCHAR(50) NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`login`),
  INDEX `fk_customers_idx` (`customerId` ASC) VISIBLE,
  INDEX `fk_roles_idx` (`roleCode` ASC) VISIBLE,
  CONSTRAINT `fk_customers`
    FOREIGN KEY (`customerId`)
    REFERENCES `elma`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles`
    FOREIGN KEY (`roleCode`)
    REFERENCES `elma`.`roles` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elma`.`orderStatuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`orderStatuses` (
  `status` VARCHAR(50) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `level` INT NULL DEFAULT 100,
  PRIMARY KEY (`status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elma`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(50) NOT NULL DEFAULT 'Новый',
  `orderDate` DATETIME NOT NULL DEFAULT now(),
  `description` VARCHAR(250) NULL,
  `clientType` INT NULL DEFAULT 0,
  `clientId` INT NULL,
  `sosudNo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_statuses_idx` (`status` ASC) VISIBLE,
  UNIQUE INDEX `sosudNo_UNIQUE` (`sosudNo` ASC) VISIBLE,
  CONSTRAINT `fk_statuses`
    FOREIGN KEY (`status`)
    REFERENCES `elma`.`orderStatuses` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elma`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`services` (
  `id` INT NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `serviceTime` INT NULL,
  `serviceDeltaTime` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elma`.`orders_arch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`orders_arch` (
  `id` INT NOT NULL,
  `userLogin` VARCHAR(50) NOT NULL,
  `serviceId` INT NOT NULL,
  `discountPercent` DECIMAL(10,2) NULL,
  `status` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_idx` (`userLogin` ASC) VISIBLE,
  INDEX `fk_services_idx` (`serviceId` ASC) VISIBLE,
  INDEX `fk_statuses_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_users_arch`
    FOREIGN KEY (`userLogin`)
    REFERENCES `elma`.`users` (`login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_services_arch`
    FOREIGN KEY (`serviceId`)
    REFERENCES `elma`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statuses_arch`
    FOREIGN KEY (`status`)
    REFERENCES `elma`.`orderStatuses` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elma`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`persons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `personEmail` VARCHAR(50) NULL,
  `personName` VARCHAR(50) NULL,
  `personBirthDate` DATE NOT NULL DEFAULT now(),
  `personPassportNo` VARCHAR(6) NULL,
  `personPassportSeria` VARCHAR(4) NULL,
  `personPhone` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elma`.`serviceStatuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`serviceStatuses` (
  `status` VARCHAR(50) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `level` INT NULL DEFAULT 100,
  PRIMARY KEY (`status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elma`.`orderDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`orderDetail` (
  `orderId` INT NOT NULL,
  `lineNo` INT NOT NULL DEFAULT 10000,
  `serviceId` INT NOT NULL,
  `serviceStatus` VARCHAR(50) NOT NULL DEFAULT 'Подготовлена',
  `userLogin` VARCHAR(50) NULL,
  `serviceDate` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`orderId`, `lineNo`),
  INDEX `orderDetail_idx` (`serviceStatus` ASC) VISIBLE,
  CONSTRAINT `orderDetail`
    FOREIGN KEY (`serviceStatus`)
    REFERENCES `elma`.`serviceStatuses` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elma`.`enterLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elma`.`enterLog` (
  `id` INT NOT NULL,
  `enterDate` VARCHAR(45) NOT NULL DEFAULT 'now()',
  `userLogin` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_idx` (`userLogin` ASC) VISIBLE,
  CONSTRAINT `fk_users`
    FOREIGN KEY (`userLogin`)
    REFERENCES `elma`.`users` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
